add task_08
BorisovDm/MADE_Algorithms_and_Data_Structures pull request #7
Opened 2019-11-23 14:27 UTC by BorisovDm

2019-12-01 14:07 UTC, smatskevich requested changes
Поправьте, пожалуйста.

2019-12-01 14:07 UTC, smatskevich commented on task_08.cpp
> +    std::vector<HashTableNode*> table;
Не надо хранить vector<HashTableNode*> - так много аллокаций. Лучше vector<HashTableNode> - память существенно сэкономите и не будет фрагментации.

2019-12-01 14:07 UTC, smatskevich commented on task_08.cpp
> +        if (node != nullptr) {
Для уменьшения вложенности обычно пишут
```
if (node == nullptr) {
  continue;
}
```

2019-12-02 18:57 UTC, BorisovDm commented on task_08.cpp
> +    std::vector<HashTableNode*> table;
Поправил.
Не разбираюсь в аллокациях, но в этом варианте нужно отдельно хранить вектор удаленных меток. Затем нельзя сравнивать значения по хеш кодам(строки дороже сравнивать, чем инты), либо отдельно хранить вектор хеш значений. Если хранить все эти дополнительные векторы, то в чем улучшение вместо использования структуры для одной ячейки?

2019-12-02 18:57 UTC, BorisovDm commented on task_08.cpp
> +        if (node != nullptr) {
согласен, поправил

2019-12-09 23:57 UTC, smatskevich commented on task_08.cpp
> +    std::vector<HashTableNode*> table;
Можно вектор структур, он предпочтительнее, но не вектор указателей на структуры.

2019-12-09 23:57 UTC, smatskevich approved these changes
Тесты пройдены.
Принято.

2019-12-10 09:17 UTC, merged